spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/flightms?zeroDateTimeBehavior=convertToNull&createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
  jackson:
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    change-log: classpath:db/changelog/diffchangelog-master.yaml
    enabled: true
    drop-first: false


server:
  port: 9000
  forward-headers-strategy: native
  servlet:
    context-path: /apis

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: debug
          filter:
            CommonsRequestLoggingFilter: debug
    root: ${ROOT_LOG_LEVEL:info}

springdoc:
  swagger-ui:
    path: swagger-ui.html
  api-docs:
    path: /api-docs





